-- DEAD PIXELS WL — secure Google-account-to-wallet allowlist backend
-- Run this once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.whitelist_applications (
  application_no bigint generated by default as identity primary key,
  id uuid not null default gen_random_uuid() unique,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null,
  wallet_address text not null,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now()
);

-- Wallet uniqueness is case-insensitive.
create unique index if not exists whitelist_wallet_lower_unique
on public.whitelist_applications (lower(wallet_address));

alter table public.whitelist_applications enable row level security;

-- Explicitly remove direct write access. RPC handles inserts.
revoke all on table public.whitelist_applications from anon, authenticated;
grant select on table public.whitelist_applications to authenticated;

-- Users can only read their own application.
drop policy if exists "read own whitelist application" on public.whitelist_applications;
create policy "read own whitelist application"
on public.whitelist_applications
for select
to authenticated
using (auth.uid() = user_id);

-- No direct insert/update/delete policy is intentionally created.
-- New applications must go through submit_whitelist().

create or replace function public.submit_whitelist(p_wallet text)
returns public.whitelist_applications
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_email text := coalesce(auth.jwt() ->> 'email', '');
  v_provider text := coalesce(auth.jwt() -> 'app_metadata' ->> 'provider', '');
  v_wallet text := lower(trim(p_wallet));
  v_result public.whitelist_applications;
  v_count bigint;
begin
  if v_user is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if v_provider <> 'google' then
    raise exception 'GOOGLE_AUTH_REQUIRED';
  end if;

  if v_email = '' then
    raise exception 'EMAIL_REQUIRED';
  end if;

  if v_wallet !~ '^0x[0-9a-f]{40}$' then
    raise exception 'INVALID_WALLET';
  end if;

  -- Serialize submissions so the 10,000 cap cannot be overshot in a race.
  perform pg_advisory_xact_lock(hashtext('dead_pixels_whitelist_submit'));

  if exists (
    select 1 from public.whitelist_applications
    where user_id = v_user
  ) then
    raise exception 'GOOGLE_ACCOUNT_ALREADY_USED';
  end if;

  if exists (
    select 1 from public.whitelist_applications
    where lower(wallet_address) = v_wallet
  ) then
    raise exception 'WALLET_ALREADY_USED';
  end if;

  select count(*) into v_count from public.whitelist_applications;
  if v_count >= 10000 then
    raise exception 'APPLICATIONS_CLOSED';
  end if;

  insert into public.whitelist_applications (user_id, email, wallet_address)
  values (v_user, v_email, v_wallet)
  returning * into v_result;

  return v_result;
end;
$$;

revoke all on function public.submit_whitelist(text) from public;
grant execute on function public.submit_whitelist(text) to authenticated;

create or replace function public.whitelist_stats()
returns table(total bigint, max_applications integer, remaining bigint, is_open boolean)
language sql
security definer
set search_path = public
as $$
  select
    count(*)::bigint as total,
    10000::integer as max_applications,
    greatest(10000 - count(*), 0)::bigint as remaining,
    (count(*) < 10000) as is_open
  from public.whitelist_applications;
$$;

revoke all on function public.whitelist_stats() from public;
grant execute on function public.whitelist_stats() to anon, authenticated;

comment on table public.whitelist_applications is
'DEAD PIXELS whitelist: exactly one application per Google-authenticated user and one application per wallet.';
